matrix:
  include:
    - language: node_js
      node_js:
        - "stable"
      install:
        - npm install -g uglify-js
      script:
        - uglifyjs ./app/static/js/working/main.js -o ./app/static/js/main.min.js
        - uglifyjs ./app/static/js/working/modal.js -o ./app/static/js/modal.min.js
    
    - language: python
      python: 
        - 3.4
      before_install:
        - "export PYTHONPATH=$PYTHONPATH:$(pwd)"
      #   - ./venv/Scripts/activate
      install: 
        - pip install -r requirements.txt
      script:
        - python freeze.py
        - python -m awscli s3 cp ./app/build s3://albert-miller/ --recursive

notifications:
  email: false