matrix:
  include:

  - language: node_js
    node_js:
    - stable
    install:
    - npm install -g travis-ci-cloudfront-invalidation
    - npm install -g uglify-js
    - npm install
    script:
    - uglifyjs ./app/static/js/working/main.js -o ./app/static/js/main.min.js
    - uglifyjs ./app/static/js/working/modal.js -o ./app/static/js/modal.min.js
    after_deploy:
    - travis-ci-cloudfront-invalidation -a $AWS_KEY_ID -s $SECRET_AWS_KEY_ID -c $DISTRIBUTION_ID -i '/*' -b $TRAVIS_BRANCH -p $TRAVIS_PULL_REQUEST

  - language: python
    python:
    - 3.4
    before_install:
    - export PYTHONPATH=$PYTHONPATH:$(pwd)
    install:
    - pip install -r requirements.txt
    script:
    - python freeze.py
    deploy:
      provider: s3
      access_key_id: $AWS_KEY_ID
      secret_access_key: $SECRET_AWS_KEY_ID
      bucket: almiller.co
      local_dir: ./app/build
      skip_cleanup: true
      region: us-east-1
      
notifications:
  email: false